
-- --------------------------------------------------------

--
-- Table structure for table `characters`
--

CREATE TABLE `characters` (
  `account_name` varchar(50) DEFAULT NULL,
  `objid` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `char_name` varchar(45) NOT NULL DEFAULT '',
  `level` int(3) UNSIGNED NOT NULL DEFAULT 0,
  `HighLevel` int(3) UNSIGNED NOT NULL DEFAULT 0,
  `Exp` bigint(11) UNSIGNED NOT NULL DEFAULT 0,
  `MaxHp` int(5) NOT NULL DEFAULT 0,
  `CurHp` int(5) NOT NULL DEFAULT 0,
  `MaxMp` int(5) NOT NULL DEFAULT 0,
  `CurMp` int(5) NOT NULL DEFAULT 0,
  `Ac` int(3) NOT NULL DEFAULT 0,
  `Str` int(3) NOT NULL DEFAULT 0,
  `BaseStr` int(3) NOT NULL DEFAULT 0,
  `Con` int(3) NOT NULL DEFAULT 0,
  `BaseCon` int(3) NOT NULL DEFAULT 0,
  `Dex` int(3) NOT NULL DEFAULT 0,
  `BaseDex` int(3) NOT NULL DEFAULT 0,
  `Cha` int(3) NOT NULL DEFAULT 0,
  `BaseCha` int(3) NOT NULL DEFAULT 0,
  `Intel` int(3) NOT NULL DEFAULT 0,
  `BaseIntel` int(3) NOT NULL DEFAULT 0,
  `Wis` int(3) NOT NULL DEFAULT 0,
  `BaseWis` int(3) NOT NULL DEFAULT 0,
  `Status` int(3) UNSIGNED NOT NULL DEFAULT 0,
  `Class` int(2) UNSIGNED NOT NULL DEFAULT 0,
  `gender` int(1) UNSIGNED NOT NULL DEFAULT 0,
  `Type` int(2) UNSIGNED NOT NULL DEFAULT 0,
  `Heading` int(2) UNSIGNED NOT NULL DEFAULT 0,
  `LocX` int(6) UNSIGNED NOT NULL DEFAULT 0,
  `LocY` int(6) UNSIGNED NOT NULL DEFAULT 0,
  `MapID` int(6) UNSIGNED NOT NULL DEFAULT 0,
  `Food` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `Alignment` int(6) NOT NULL DEFAULT 0,
  `Title` varchar(35) NOT NULL DEFAULT '',
  `ClanID` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `Clanname` varchar(45) NOT NULL,
  `ClanRank` int(3) NOT NULL DEFAULT 0,
  `ClanContribution` int(8) NOT NULL DEFAULT 0,
  `ClanWeekContribution` int(8) NOT NULL DEFAULT 0,
  `pledgeJoinDate` int(10) NOT NULL DEFAULT 0,
  `pledgeRankDate` int(10) NOT NULL DEFAULT 0,
  `notes` varchar(60) NOT NULL,
  `BonusStatus` int(4) NOT NULL DEFAULT 0,
  `ElixirStatus` int(2) NOT NULL DEFAULT 0,
  `ElfAttr` int(2) NOT NULL DEFAULT 0,
  `PKcount` int(6) NOT NULL DEFAULT 0,
  `ExpRes` int(10) NOT NULL DEFAULT 0,
  `PartnerID` int(10) NOT NULL DEFAULT 0,
  `AccessLevel` int(6) UNSIGNED NOT NULL DEFAULT 0,
  `OnlineStatus` int(2) UNSIGNED NOT NULL DEFAULT 0,
  `HomeTownID` int(2) NOT NULL DEFAULT 0,
  `Contribution` int(10) NOT NULL DEFAULT 0,
  `HellTime` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `Banned` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `Karma` int(10) NOT NULL DEFAULT 0,
  `LastPk` datetime DEFAULT NULL,
  `DeleteTime` datetime DEFAULT NULL,
  `ReturnStat` bigint(10) NOT NULL,
  `lastLoginTime` datetime DEFAULT NULL,
  `lastLogoutTime` datetime DEFAULT NULL,
  `BirthDay` int(11) DEFAULT NULL,
  `PC_Kill` int(6) DEFAULT NULL,
  `PC_Death` int(6) DEFAULT NULL,
  `Mark_Count` int(10) NOT NULL DEFAULT 60,
  `TamEndTime` datetime DEFAULT NULL,
  `SpecialSize` int(3) NOT NULL DEFAULT 0,
  `HuntPrice` int(10) DEFAULT NULL,
  `HuntText` varchar(30) DEFAULT NULL,
  `HuntCount` int(10) DEFAULT NULL,
  `RingAddSlot` int(3) DEFAULT 0,
  `EarringAddSlot` int(3) DEFAULT 0,
  `BadgeAddSlot` int(3) DEFAULT 0,
  `ShoulderAddSlot` int(3) DEFAULT 0,
  `fatigue_point` int(3) NOT NULL DEFAULT 0,
  `fatigue_rest_time` datetime DEFAULT NULL,
  `EMETime` datetime DEFAULT NULL,
  `EMETime2` datetime DEFAULT NULL,
  `PUPLETime` datetime DEFAULT NULL,
  `TOPAZTime` datetime DEFAULT NULL,
  `EinhasadGraceTime` datetime DEFAULT NULL,
  `EinPoint` int(11) DEFAULT 0,
  `EinCardLess` int(2) NOT NULL DEFAULT 0,
  `EinCardState` int(3) NOT NULL DEFAULT 0,
  `EinCardBonusValue` int(1) NOT NULL DEFAULT 0,
  `ThirdSkillTime` datetime DEFAULT NULL,
  `FiveSkillTime` datetime DEFAULT NULL,
  `SurvivalTime` datetime DEFAULT NULL,
  `potentialTargetId` int(10) NOT NULL DEFAULT 0,
  `potentialBonusGrade` int(1) NOT NULL DEFAULT 0,
  `potentialBonusId` int(3) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=euckr COLLATE=euckr_korean_ci;

--
-- RELATIONSHIPS FOR TABLE `characters`:
--
