
-- --------------------------------------------------------

--
-- Table structure for table `item_enchant_ablity`
--

CREATE TABLE `item_enchant_ablity` (
  `itemId` int(3) NOT NULL DEFAULT 0,
  `name` varchar(70) NOT NULL,
  `desc_kr` varchar(45) DEFAULT NULL,
  `enchant` int(2) NOT NULL DEFAULT 0,
  `ac_bonus` int(2) NOT NULL DEFAULT 0,
  `ac_sub` int(3) NOT NULL DEFAULT 0,
  `str` int(2) NOT NULL DEFAULT 0,
  `con` int(2) NOT NULL DEFAULT 0,
  `dex` int(2) NOT NULL DEFAULT 0,
  `int` int(2) NOT NULL DEFAULT 0,
  `wis` int(2) NOT NULL DEFAULT 0,
  `cha` int(2) NOT NULL DEFAULT 0,
  `shortDamage` int(2) NOT NULL DEFAULT 0,
  `shortHit` int(2) NOT NULL DEFAULT 0,
  `shortCritical` int(2) NOT NULL DEFAULT 0,
  `longDamage` int(2) NOT NULL DEFAULT 0,
  `longHit` int(2) NOT NULL DEFAULT 0,
  `longCritical` int(2) NOT NULL DEFAULT 0,
  `spellpower` int(2) NOT NULL DEFAULT 0,
  `magicHit` int(2) NOT NULL DEFAULT 0,
  `magicCritical` int(2) NOT NULL DEFAULT 0,
  `magicDamage` int(2) NOT NULL DEFAULT 0,
  `maxHp` int(3) NOT NULL DEFAULT 0,
  `maxMp` int(3) NOT NULL DEFAULT 0,
  `hpRegen` int(2) NOT NULL DEFAULT 0,
  `mpRegen` int(2) NOT NULL DEFAULT 0,
  `baseHpRate` int(2) NOT NULL DEFAULT 0,
  `baseMpRate` int(2) NOT NULL DEFAULT 0,
  `attrFire` int(2) NOT NULL DEFAULT 0,
  `attrWater` int(2) NOT NULL DEFAULT 0,
  `attrWind` int(2) NOT NULL DEFAULT 0,
  `attrEarth` int(2) NOT NULL DEFAULT 0,
  `attrAll` int(2) NOT NULL DEFAULT 0,
  `mr` int(2) NOT NULL DEFAULT 0,
  `carryBonus` int(3) NOT NULL DEFAULT 0,
  `dg` int(2) NOT NULL DEFAULT 0,
  `er` int(2) NOT NULL DEFAULT 0,
  `me` int(2) NOT NULL DEFAULT 0,
  `reduction` int(2) NOT NULL DEFAULT 0,
  `reductionEgnor` int(2) NOT NULL DEFAULT 0,
  `reductionMagic` int(2) NOT NULL DEFAULT 0,
  `reductionPercent` int(2) NOT NULL DEFAULT 0,
  `PVPDamage` int(2) NOT NULL DEFAULT 0,
  `PVPReduction` int(2) NOT NULL DEFAULT 0,
  `PVPReductionPercent` int(2) NOT NULL DEFAULT 0,
  `PVPReductionEgnor` int(2) NOT NULL DEFAULT 0,
  `PVPReductionMagic` int(2) NOT NULL DEFAULT 0,
  `PVPReductionMagicEgnor` int(2) NOT NULL DEFAULT 0,
  `abnormalStatusDamageReduction` int(2) NOT NULL DEFAULT 0,
  `abnormalStatusPVPDamageReduction` int(2) NOT NULL DEFAULT 0,
  `PVPDamagePercent` int(2) NOT NULL DEFAULT 0,
  `registBlind` int(2) NOT NULL DEFAULT 0,
  `registFreeze` int(2) NOT NULL DEFAULT 0,
  `registSleep` int(2) NOT NULL DEFAULT 0,
  `registStone` int(2) NOT NULL DEFAULT 0,
  `toleranceSkill` int(2) NOT NULL DEFAULT 0,
  `toleranceSpirit` int(2) NOT NULL DEFAULT 0,
  `toleranceDragon` int(2) NOT NULL DEFAULT 0,
  `toleranceFear` int(2) NOT NULL DEFAULT 0,
  `toleranceAll` int(2) NOT NULL DEFAULT 0,
  `hitupSkill` int(2) NOT NULL DEFAULT 0,
  `hitupSpirit` int(2) NOT NULL DEFAULT 0,
  `hitupDragon` int(2) NOT NULL DEFAULT 0,
  `hitupFear` int(2) NOT NULL DEFAULT 0,
  `hitupAll` int(2) NOT NULL DEFAULT 0,
  `potionPlusDefens` int(2) NOT NULL DEFAULT 0,
  `potionPlusPercent` int(2) NOT NULL DEFAULT 0,
  `potionPlusValue` int(2) NOT NULL DEFAULT 0,
  `hprAbsol32Second` int(2) NOT NULL DEFAULT 0,
  `mprAbsol64Second` int(2) NOT NULL DEFAULT 0,
  `mprAbsol16Second` int(2) NOT NULL DEFAULT 0,
  `imunEgnor` int(2) NOT NULL DEFAULT 0,
  `expBonus` int(2) NOT NULL DEFAULT 0,
  `einBlessExp` int(2) NOT NULL DEFAULT 0,
  `rest_exp_reduce_efficiency` int(2) NOT NULL DEFAULT 0,
  `fowSlayerDamage` int(2) NOT NULL DEFAULT 0,
  `titanUp` int(2) NOT NULL DEFAULT 0,
  `stunDuration` int(2) NOT NULL DEFAULT 0,
  `tripleArrowStun` int(2) NOT NULL DEFAULT 0,
  `vanguardTime` int(2) NOT NULL DEFAULT 0,
  `strangeTimeIncrease` int(4) NOT NULL DEFAULT 0,
  `strangeTimeDecrease` int(4) NOT NULL DEFAULT 0,
  `hpPotionDelayDecrease` int(4) NOT NULL DEFAULT 0,
  `hpPotionCriticalProb` int(4) NOT NULL DEFAULT 0,
  `increaseArmorSkillProb` int(4) NOT NULL DEFAULT 0,
  `returnLockDuraion` int(2) NOT NULL DEFAULT 0,
  `attackSpeedDelayRate` int(3) NOT NULL DEFAULT 0,
  `moveSpeedDelayRate` int(3) NOT NULL DEFAULT 0,
  `magicName` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=euckr COLLATE=euckr_korean_ci;

--
-- RELATIONSHIPS FOR TABLE `item_enchant_ablity`:
--
